server:
  port: 8080

spring:
  application:
    name: kafkaTest

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      group-id: consumer_group01
#      auto-offset-reset: earliest

topic:
  name1: email